import '../app/data/models/product_model.dart';
import 'constants.dart';

class DummyHelper {
  const DummyHelper._();

  static List<ProductModel> products = [
    ProductModel(
      id: 1,
      image: Constants.product1,
      name: 'Felt side bag',
      artist: 'Salina Yadav',
      quantity: 0,
      price: 2500,
      rating: 4.5,
      reviews: '500 reviews',
      isFavorite: false,
    ),
    ProductModel(
        id: 2,
        image: Constants.product2,
        name: 'Thangka Painting',
        artist: ' Jambu Sherpa',
        quantity: 0,
        price: 25000,
        rating: 4.4,
        reviews: '10k reviews',
        isFavorite: false),
    ProductModel(
        id: 3,
        image: Constants.product3,
        name: 'One Piece Dress',
        artist: 'The dress thamel',
        quantity: 0,
        price: 3000,
        rating: 4.3,
        reviews: '2k reviews',
        isFavorite: false),
    ProductModel(
        id: 4,
        image: Constants.product4,
        name: 'Gold Statue',
        artist: 'Naresh Barma',
        quantity: 0,
        price: 25000,
        rating: 4.2,
        reviews: '3k reviews',
        isFavorite: false),
    ProductModel(
        id: 5,
        image: Constants.product5,
        name: 'Namaste Mountain Carved Stone Panel',
        artist: 'Salman Lama',
        quantity: 0,
        price: 39.99,
        rating: 4.1,
        reviews: '2.6k reviews',
        isFavorite: false),
    ProductModel(
        id: 6,
        image: Constants.product6,
        name: 'Lava Stone Bracelet',
        artist: 'Soni Sherpa',
        quantity: 0,
        price: 800,
        rating: 4.0,
        reviews: '1k reviews',
        isFavorite: false),
    ProductModel(
        id: 7,
        image: Constants.product7,
        name: 'Straw Baskets',
        artist: ' Hemanta Acharya',
        quantity: 0,
        price: 500,
        rating: 4.0,
        reviews: '1k reviews',
        isFavorite: false),
    ProductModel(
        id: 8,
        image: Constants.product8,
        name: 'Wooden Door with Bell Decor',
        artist: 'prikyang Shrestha',
        quantity: 0,
        price: 2000,
        rating: 4.0,
        reviews: '1.5k reviews',
        isFavorite: false),
    ProductModel(
        id: 9,
        image: Constants.product9,
        name: 'Stone Side Bag',
        artist: ' Muskan Jha ',
        quantity: 0,
        price: 3000,
        rating: 4.0,
        reviews: '300 reviews',
        isFavorite: false),
    ProductModel(
        id: 10,
        image: Constants.product10,
        name: 'Wooden Pashupati Temple Model',
        artist: 'garima Shrestha',
        quantity: 0,
        price: 4000,
        rating: 4.0,
        reviews: '150 reviews',
        isFavorite: false),
  ];
}
